Centro_Proyecto/Centro_Proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Centro_Proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('apps.home.urls', namespace="home")),
    url(r'', include ('apps.usuario.urls',namespace="usuario")),
    url(r'', include('apps.paciente.urls',namespace="paciente")),
    url(r'', include('apps.medicacion.urls',namespace="medicacion")),
    url(r'', include('apps.receta.urls',namespace="receta")),
    url(r'', include('apps.seguro.urls', namespace="seguro")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),### para servir imagenes
)
 

Centro_Proyecto/apps/medicacion/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	
	url(r'^receta/(\d+)$' , "apps.medicacion.views.MedicacionPacientes", name="medicacionPacientes"),
	url(r'^recetaPacientes/(\d+)$' , "apps.medicacion.views.recetaPacientes", name="recetaPacientes"),
	url(r'^agregarMedicamento/(\d+)$' , "apps.medicacion.views.agregarMedicamento", name="agregarMedicamento"),
	url(r'^eliminarMedicamento/(\d+)$' , "apps.medicacion.views.eliminarMedicamento", name="eliminarMedicamento"),
	url(r'^respuesta$' , "apps.medicacion.views.respuesta", name="respuesta"),
	url(r'^respuesta2$' , "apps.medicacion.views.respuesta", name="respuesta"),
	
)

Centro_Proyecto/apps/receta/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	
	#url(r'^receta/(\d+)$' , "apps.medicacion.views.MedicacionPacientes", name="MedicacionPacientes"),
	url(r'^agregarReceta(\d+)$' , "apps.receta.views.agregarReceta", name="agregarReceta"),
	url(r'^obtener_Nombre$' , "apps.receta.views.obtener_Nombre", name="obtener_Nombre"),
	url(r'^prueba$' , "apps.receta.views.prueba", name="prueba"),
	
)

Centro_Proyecto/apps/medicacion/models.py
from django.db import models
from apps.paciente.models import Paciente
#from apps.receta.models import Receta

class Medicamento(models.Model):
	nombre=models.CharField(max_length=140)
	cantidad=models.PositiveIntegerField()
	informacion_Extra=models.CharField(max_length=140)
	Tab="Tab"
	Mg="Mg"
	Unidad="Unidad"
	Ml="Ml"
	Unidades=((Tab, "Tab"), (Unidad, "Unidad"),(Ml, "Ml"),(Mg, "Mg"))
	unidad=models.CharField(max_length=20, choices=Unidades,default=Tab)
	#receta=models.OneToOneField(Receta)
	paciente=models.ForeignKey(Paciente)
		
	def __unicode__(self):
		return  self.nombre

Centro_Proyecto/apps/receta/models.py
from django.db import models
from apps.paciente.models import Paciente
''''
class Receta(models.Model):
	descripcion=models.CharField(max_length=50)
	fecha=models.DateField(auto_now=True)
	libro=models.CharField(max_length=50)
	paciente=models.ForeignKey(Paciente)
	
	def __unicode__(self):
		return self.descripcion
		'''

Centro_Proyecto/apps/medicacion/forms.py
from models import Medicamento
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class MedicamentoForm(ModelForm):
	class Meta:
		model=Medicamento
		
	def __init__(self, *args, **kwargs):
		super(MedicamentoForm, self).__init__(*args, **kwargs)
		self.fields['nombre'].widget.attrs.update({'placeholder' : 'Ingrese el nombre','id':'medicacionF', 'title': "Se necesita un nombre(solo numeros)", 'class':"form-control", 'type':'text', 'required':'True'})	
		self.fields['cantidad'].widget.attrs.update({'placeholder' : 'Ingrese el cantidad','id':'medicacionF', 'title': "Se necesita un cantidad", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarNumeros(event)"})
		self.fields['informacion_Extra'].widget.attrs.update({'placeholder' : 'Ingrese el informacion_Extra','id':'medicacionF', 'title': "Se necesita un informacion_Extra(solo numeros)", 'class':"form-control", 'type':'text', 'required':'False'})	
		

Centro_Proyecto/apps/medicacion/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from apps.paciente.models import Paciente
from models import Medicamento
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render_to_response
from forms import MedicamentoForm
from datetime import datetime, timedelta, date
from django.template.context import RequestContext

##listado de Medicamentos##
def MedicacionPacientes(request,id_paciente):
	hora=datetime.now()
	dia=hora.day
	pac=Paciente.objects.get(pk=id_paciente)
	medicamento=Medicamento.objects.filter(paciente=pac)
	template="medicacion/medicacionPacientes.html"
	return render(request,template,locals())

## Eliminar medicamento
def eliminarMedicamento(request, id_medicamento):
	medicamento=Medicamento.objects.get(pk=id_medicamento)
	medicamento.delete()
	template="medicacion/respuesta2.html"
	return render_to_response(template,context_instance=RequestContext(request,locals()))



def respuesta(request):
	template="medicacion/respuesta.html"
	return render(request, template)

def respuesta2(request):
	template="medicacion/respuesta.html"
	return render(request, template)

###Agreagr medicamentos##
def agregarMedicamento(request,id_paciente):
	pac=Paciente.objects.get(pk=id_paciente)
	medicamento=Medicamento.objects.filter(paciente=pac)
	
	if request.POST:
		form=MedicamentoForm(request.POST, request.FILES)
		if form.is_valid():
			medicamento=form.save(commit=False)
			medicamento.usuario=request.user
			medicamento.save()
			template="medicacion/respuesta.html"
			return render_to_response(template,context_instance=RequestContext(request,locals()))
			
	else:
		form=MedicamentoForm()
	

	template="medicacion/medicamentoForm.html"
	return render_to_response(template,context_instance=RequestContext(request,locals()))

##receta
def recetaPacientes(request,id_paciente):
	hora=datetime.now()
	dia=hora.day
	pac=Paciente.objects.get(pk=id_paciente)
	medicamento=Medicamento.objects.filter(paciente=pac)
	template="medicacion/Receta.html"
	return render(request,template,locals())

Centro_Proyecto/apps/receta/views.py
from django.shortcuts import render, render_to_response,redirect
from django.http import HttpResponseRedirect
from django.template import RequestContext
#from .form import RecetaForm
#from .models import Receta
'''
def agregarReceta(request,id_paciente):
	if request.method =='POST':
		form=Receta(request.POST)
		if form.is_valid():
			
	else:
		form=Receta()
	
	template= 'medicacion/Receta.html'
	return render_to_response(template,context_instance=RequestContext(request,locals()))	

''''
'''
def agregarReceta(request):
	template="receta/agregarReceta.html"
	nombre="Mario"
	return render(request, template, locals())

def prueba(request):
	Nombrew=request.GET.get["Nombre"]
	template="receta/prueba2.html"
	return render(request,template, locals())

def obtener_Nombre(request):
	if request.method =='POST':
		form=PruebaForm(request.POST)
		if form.is_valid():
			#Nombre=Receta(nombre=request.GET['su_nombre']) 
			#Nombre.save()
			Nombre=request.POST['su_nombre']
			Rec=Receta.objects.filter(nombre=Nombre)

			template="medicacion/receta.html"
			return render_to_response(template,context_instance=RequestContext(request,locals()))
			#return HttpResponseRedirect('/prueba')
	else:
		form=PruebaForm()
	
	template= 'receta/prueba.html'
	return render_to_response(template,context_instance=RequestContext(request,locals()))

'''

Centro_Proyecto/templates/medicacion/MedicacionPdf.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Medicacion Pdf</title>
</head>
<body>
	
</body>
</html>

Centro_Proyecto/templates/medicacion/Receta.html
{% extends "base.html" %}
{%block title%}Receta{%endblock%}
		{% load static from staticfiles %}

{% block contenido %}
	
		
	
	<div>
	<p id="tit2"> 
		Centro de Diálisis Cornelio Samaniego Valdivieso Cía. Ltda 
	</p>

	<center>
	<div id="recetario-contenedor" style="width:100%;">
		<table id="tabPrincipal2" class="table table-striped recetario">
			<tr id="noM">
				<td id="titulo" class="encabezado">
					<center>
						CENTRO DE DIÁLISIS<br>CORNELIO SAMANIEGO VALDIVIESO Cía. Ltda 
					</center>
				</td>
				<td id="titulo" class="encabezado">
					<center>
						CENTRO DE DIÁLISIS<br>CORNELIO SAMANIEGO VALDIVIESO Cía. Ltda
					</center>
				</td>
			</tr>
			<tr>
				<td class="paciente">
					Fecha: {{hora}}<br>Nombre: {{pac.nombre}} {{pac.apellido}}
				</td>
				<td class="paciente">
					Fecha: {{hora}}<br>Nombre: {{pac.nombre}} {{pac.apellido}}
				</td>
			</tr>
			<tr>
				<td><span class="apartado">Rp.</span></td><td><span class="apartado"> Indicaciones: </span></td>
			</tr>
			<tr>
				<td>
					<form>
					<div class="contenido">
						<table id="tabla1" class="table table-striped">
							{% for med in medicamento%}
							<tr>
								<td>{{med.nombre}}</td>
								<td>
									<input  type="text" id="num" class="form-control" placeholder="Cant" value="{{med.cantidad}}" >
								</td>
								<td id="BdUnidad">{{med.unidad}}</td>
							</tr>
							{% endfor %}
						</table>
					</div>
					</form>
				</td>
				<td>
					<form>
					<div class="contenido">
						<table>
							<tr>
								<td>
									<ul class="list-group">
									{%for med in medicamento%}
									  <li class="list-group-item">{{med.nombre}}</li>
									  <li class="list-group-item"> <textarea rows="1" style="width:100%;">{{med.informacion_Extra}}</textarea> </li>
									  {%endfor%}
									 
									</ul>
								</td>
							</tr>
						</table>
						</div>
					</form>
				</td>
			</tr>

			<tr>
		        <td>
		            <footer id="recetario-footer" >
		                <article>
		                    <h4>Dr. Jorge Leonardo Cabrera L.</h4>
		                    <h4>Nefrólogo</h4>
		                    <h5>Reg: Libro 001 Folio 0165 N# 494</h5>
		                </article>
		            </footer>
		        </td>
		        <td>
		            <footer id="recetario-footer">
		                <article>
		                    <h4>Dr. Jorge Leonardo Cabrera L.</h4>
		                    <h4>Nefrólogo</h4>
		                    <h5>Reg: Libro 001 Folio 0165 N# 494</h5>
		                </article>
		            </footer>
		        </td>
		    </tr>
		
			<tr>
				<td><nav id="submenu"></nav></td>
				<td id="h">
					<nav id="submenu">
						<center><button type="button" class="btn btn-primary">Guardar</button>&nbsp&nbsp
						<!--<a  value="Imprimir" class="btn btn-warning" onClick="window.print()">Imprimir</a></center>-->
						<a  value="Imprimir" class="btn btn-warning" onClick="window.print()">Imprimir</a></center>
					</nav>
				</td>
			</tr>
		</table>
	</div>
	</center>

</div>
	

							<div id="firma">
								<br>
								<center>Dr. Jorge Leonardo Cabrera L.</center>
								<center>Nefrólogo</center>
							</div>


{% endblock %}

Centro_Proyecto/templates/medicacion/Receta2.html
{% extends "base.html" %}
{%block title%}Receta{%endblock%}
		{% load static from staticfiles %}

{% block contenido %}
	
	<div id="imprime">
		<div id="logo"> 
        	<img src="{% static 'img/centro.jpg' %}"> 
   		</div>
	<center><table id="tabPrincipal" class="table table-striped">
		<tr id="noM">
			<td id="titulo"><center>Centro de Diálisis<br>Cornelio Samaniego Valdivieso Cía. Ltda &nbsp&nbsp&nbsp&nbsp</center></td><td id="titulo"><center>Centro de Diálisis<br>Cornelio Samaniego Valdivieso Cía. Ltda</center></td>
		</tr>
		<tr>
			<td>Fecha: {{hora}}<br>Nombre: {{pac.nombre}}</td><td>Fecha: {{hora}}<br>Nombre: {{pac.nombre}}</td>
		</tr>
		<tr>
			<td>Rp.</td><td>Indicaciones:</td>
		</tr>
		<tr>
			<td>
			<form>
				<table id="tabla1" class="table table-striped">
					{% for med in medicamento%}
					<tr>
						<td>{{med.nombre}}</td>
						
						<td><input  type="text" id="num" class="form-control" placeholder="Cant" value="{{med.cantidad}}" ></td>

						<td id="BdUnidad">{{med.unidad}}</td>
					</tr>
					{% endfor %}

				</table>

			</form>
			</td>
			<td>
				<form>
					<table d="tabla2">
						<tr>
							<td>
								
								<ul class="list-group">
								{%for med in medicamento%}
								  <li class="list-group-item">{{med.nombre}}</li>
								  <li class="list-group-item"> <textarea rows="1" cols="50" >{{med.informacion_Extra}}</textarea> </li>
								  {%endfor%}
								 
								</ul>
							</td>
						</tr>
						<tr>
							<td id="firma">
							<center>Dr. Jorge Leonardo Cabrera L.</center>
							 <center>Nefrólogo</center>
							 </td>
						</tr>
					</table>
				</form>
			</td>
		</tr>

		<tr>
			<td><nav id="submenu">
				
			</nav></td>
			<td id="h"><nav id="submenu">
				<center><button type="button" class="btn btn-primary">Guardar</button>&nbsp&nbsp
				<!--<a  value="Imprimir" class="btn btn-warning" onClick="window.print()">Imprimir</a></center>-->
				<a  value="Imprimir" class="btn btn-warning" onClick="window.print()">Imprimir</a></center>
				
			</nav></td>

		</tr>
	</table></center>
</div>
	
<script type="text/javascript">
	function prints(imprime)
	{
		
		var ficha=document.getElementById(imprime);
		var a=
		var ventimp=window.open(' ','popimpr');
		ventimp.document.write(ficha.innerHTML);
		ventimp.document.close();
		ventimp.print();
		ventimp.close();
		
	}
	

</script>

 <style type="text/css">
 html,body,form
{
 margin:0;
 padding:0;
}
 @page{
   		margin: 2cm;
 }
 @media print {
    #imprime {
		width: 100px;
    	

    }
    #tit1{
    	text-align: center;
    	margin-left: 140px;
    }
    
    #h{
    	display: none;
    }
    #firma1{
    	margin-left: 30px;
    }

    #tabPrincipal{
    	font-size: 25px;
    	float: left;
		
    }
    #tabla2{
    	float: right;
    	margin-right: 30px;

    }
    #tabla1{
    	float: right;
    	margin-right: 30px;
    	margin-top: 30px;
    	font-size: 30px;
    }
    #pacienteF{
    	color: green;
    }
  
	#footer,#cerrar, #usuario, nav, buscador-form{
		display: none;
	}

	#tabPrincipal #titulo {
		margin-left: -300px;
		font-size: 40px;
	}
	#BdUnidad, #num, li{
		font-size: 20px;	
	}
	#logo{
		margin-left: 100px;
		margin-top: -80px;
		width: 80px;
		border-radius: 50%;
		margin-bottom: 70px;
	}
	#logo img{
		border-radius: 50%;
	}
	#titulo{
		text-align: center;
	}
	#firma{
		font-size: 30px;
	}
}

</style>


{% endblock %}

Centro_Proyecto/templates/medicacion/medicacionPacientes.html
{%extends "base.html"%}
	{%block title%}Medicamentos{%endblock%}
	{%block contenido%}
<div class="contenedor">
	<div class="medTitulo">
		<h2 class="text-info">Medicamentos</h2>
	</div>
	
	<section>
		<article>
			<figure id="fotoMed">
				<img src="{{pac.foto.url}}" alt="usuario">
				<h4>paciente:</h4>	
				<figcaption>{{pac.nombre}}</figcaption>
				<figcaption>{{pac.apellido}}</figcaption>
			</figure>
		</article>
	</section>
	<section>
		<article id="medicamento">
				<table class="table table-hover">
					 <tr>
						<th>Administrar</th>
	            		<th>Medicamento</th>
	            		<th>Cantidad</th>
	            		<th>Unidad</th>
	            		<th>Indicaciones</th>
	            	 </tr>
	            	 {%for med in medicamento%}

	            	 <tr>
	            	 	<td>
						<a href="{%url "medicacion:eliminarMedicamento" med.pk%}" class="btn btn-danger">X</a>
						</td>
						
	            		<td>{{med.nombre}}</td>
	            		<td>{{med.cantidad}}</td>
	            		<td>{{med.unidad}}</td>
	            		<td>{{med.informacion_Extra}}</td>
	         
	        	  	 </tr>
	        	  	 {%endfor%}
				</table>
		<div class="listButtons">
			<a href="{% url "medicacion:agregarMedicamento" pac.pk%}" class="btn btn-default">Agregar Medicamentos</a>
			<a href="{%url "medicacion:recetaPacientes" pac.pk%}" class="btn btn-default">Nueva Receta</a>

		</div>
		</article>
	</section>
</div>	
{% endblock %}

Centro_Proyecto/templates/medicacion/medicamentoForm.html
{% extends "base.html" %}
{% block contenido %}


	<div id="contenidoH">
	<div class="panel panel-default">
  		<div class="panel-heading">
			<p class="text-info" id="registrar">Registrar Nuevo medicamento</p>		
  		</div>
	<div class="panel-body">
		<div class="formularioPac">
	{%for field in form%}
		{% if field.errors%}
			<div id="Errores">{{field.errors}}</div>
		{%endif%}
	{% endfor %}
	<form method="POST" enctype="multipart/form-data" class="form-group">
			<div action ="" id="form">
				{%csrf_token%}	
					<label for="Nombre">Nombre del medicamento: </label>
								<div >{{form.nombre}}</div>
								<label for="cantidad">Cantidad </label>
								<div >{{form.cantidad}}</div>
								<label for="Informacion">Informacion : </label>
								<div>{{form.informacion_Extra}}</div>					
								<label  for="unidad">Unidad: </label>
								<div id="medicacionF">{{form.unidad}}</div>					
								<input class="form-control" id="medicacionF" maxlength="140" name="paciente" onkeydown="return validarLetras(event)" placeholder="Ingrese el informacion_Extra" required="False" title="Se necesita un informacion_Extra(solo numeros)" type="hidden" value="{{pac.pk}}">
								
				<br>
								

				<center><input type="submit" class="btn btn-primary" value="Guardar Datos de medicamentos">	</center>
					
			</div>
		</form>
		</div>
		</div>
		</div>
</div>
{% endblock %}

Centro_Proyecto/templates/medicacion/respuesta.html
{% extends "base.html" %}
{% block contenido %}


	<div id="contenidoH">
	<div class="panel panel-default">
  		<div class="panel-heading">
			<p class="text-info" id="registrar">Registrar Nuevo medicamento</p>		
  		</div>
	<div class="panel-body">
		<div class="formularioPac">
			<p class="text-danger">El medicamento ha sido ingresado con exito</p>				
			<a href="{% url "medicacion:medicacionPacientes" pac.pk %}">Regresar</a>
		</div>
		</form>
		</div>
		</div>
		</div>
</div>
{% endblock %}

Centro_Proyecto/templates/medicacion/respuesta2.html
{% extends "base.html" %}
{% block contenido %}


	<div id="contenidoH">
	<div class="panel panel-default">
  		<div class="panel-heading">
			<p class="text-info" id="registrar">Registrar Nuevo medicamento</p>		
  		</div>
	<div class="panel-body">
		<div class="formularioPac">
			<p class="text-danger">El medicamento ha sido Eliminado</p>				
			
		</div>
		</form>
		</div>
		</div>
		</div>
</div>
{% endblock %}