Centro_Proyecto/Centro_Proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Centro_Proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('apps.home.urls', namespace="home")),
    url(r'', include ('apps.usuario.urls',namespace="usuario")),
    url(r'', include('apps.paciente.urls',namespace="paciente")),
    url(r'', include('apps.medicacion.urls',namespace="medicacion")),
    url(r'', include('apps.receta.urls',namespace="receta")),
    url(r'', include('apps.seguro.urls', namespace="seguro")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),### para servir imagenes
)
 

Centro_Proyecto/apps/paciente/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^listaPacientes$' , "apps.paciente.views.listaPacientes", name='listaPacientes'),
	url(r'^eliminarPaciente/(\d+)$' , "apps.paciente.views.eliminarPaciente", name='eliminarPaciente'),
	url(r'^agregarPaciente$' , "apps.paciente.views.agregarPaciente", name="agregarPaciente"),
	url(r'^buscarPaciente$' , "apps.paciente.views.buscarPaciente", name="buscarPaciente"),
	url(r'^cerrar$' , "apps.paciente.views.cerrar", name="cerrar"),
	url(r'^historia/(\d+)$' , "apps.paciente.views.historia", name="historia"),


)

Centro_Proyecto/apps/seguro/urls.py
from django.conf.urls import patterns, include, url
#from .views import SeguroList

urlpatterns = patterns('',
	#url(r'^ListaSeguro$' , SeguroList.as_view()),
	url(r'^agregarSeguro$' , 'apps.seguro.views.agregarSeguro' ,name="agregarSeguro"),
	url(r'^asincronoSeguro$' , 'apps.seguro.views.asincronoSeguro' ,name="asincronoSeguro"),

)

Centro_Proyecto/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" charset="utf-8">
	<meta http-equiv="content-type" content="text/html"/>
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	{% load static from staticfiles %}
    <link rel="stylesheet" type="text/css" href="{%static 'css/normalize.css'%}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.css'%}" media="screen">	
	<link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}" media="screen">	
	<link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap-theme.css'%}" media="screen">	
	<link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap-theme.min.css'%}" media="screen">

	
	<!-- Estilos para imprimir -->
	<link rel="stylesheet" type="text/css" href="{%static 'css/imprimir-receta.css'%}" media="print">
	

	  <link rel="icon" type="image/x-icon" href="{%static 'img/favicon.ico'%}" />
    <link rel="stylesheet" type="text/css" href="{%static 'css/estilo.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/estilo1.css'%}" media="screen">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.slides.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/interactividad.js'%}"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>   
	<script type="text/javascript" src="{% static 'js/animaciones.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/Validadores.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/llamadasAsincronas.js'%}"></script>


	
	<title>{%block title%}{%endblock%}</title>
	
</head>
<body>
<!--ENCABEZADO CON HEADER-->
    <header>
               
        <!--IMAGEN DE LA IZQUIERDA--> 

        <div class="contenedor">
            <div class="imagenIzq">
                <figure>
                    <img src="{%static 'img/logo1.png' %}" alt="Centro de Dialisis">
                </figure>
            </div>
            
            <!---MENU-->
            <nav class="menu">
                <ul>
                    <li><a href="{%url "paciente:listaPacientes" %}">Inicio</a></li>
					<li><a href="{%url "paciente:agregarPaciente"%}">Agregar Pacientes</a></li>
					<li><a href="{%url "seguro:agregarSeguro"%}">Agregar Seguro</a></li>
					<li><a href="{%url "paciente:cerrar"%}">Cerrar sesion</a></li>
					
					<p id="usuario" class="text-default">Bienvenido {{request.user}}</p>
					
                </ul>
            </nav>
        </div>

    </header>
   
    

	{% block contenido %} 
			
	{% endblock %}

	<!--FOOTER-->

  	
		
</body>
</html>