Centro_Proyecto/Centro_Proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Centro_Proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('apps.home.urls', namespace="home")),
    url(r'', include ('apps.usuario.urls',namespace="usuario")),
    url(r'', include('apps.paciente.urls',namespace="paciente")),
    url(r'', include('apps.medicacion.urls',namespace="medicacion")),
    url(r'', include('apps.receta.urls',namespace="receta")),
    url(r'', include('apps.seguro.urls', namespace="seguro")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),### para servir imagenes
)
 

Centro_Proyecto/apps/home/urls.py
from django.conf.urls import patterns, include, url
from .views import IndexView 

urlpatterns = patterns('',
	url(r'^$' , IndexView.as_view(), name="home"),
	

)

Centro_Proyecto/apps/usuario/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
	url(r'^entrar$' , 'apps.usuario.views.entrar', name="entrar"),

)

Centro_Proyecto/apps/usuario/models.py
from django.db import models

Centro_Proyecto/apps/usuario/forms.py
from models import *
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class UserCreationEmailForm(UserCreationForm):
	email=forms.EmailField()
	class Meta:
		model=User
		fields=('username','email')


class EmailAuthenticationForm(forms.Form):
	email=forms.EmailField()
	password=forms.CharField(label='contrasena', widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		self.user_cache=None
		super(EmailAuthenticationForm, self).__init__(*args, **kwargs)

	def clean(self):
		email=self.cleaned_data.get('email')
		password=self.cleaned_data.get('password')

		self.user_cache=authenticate(email=email, password=password)

		if self.user_cache is None:
			raise forms.ValidationError('Usuario Incorrecto')
		elif not self.user_cache.is_active:
			raise forms.ValidationError('Usuario Inactivo')

		return self.cleaned_data


	def get_user(self):
		return self.user_cache

Centro_Proyecto/apps/usuario/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,authenticate, logout
from django.contrib.auth.models import User
from django.template.loader import get_template
from django.template.context import RequestContext
from django.http import HttpResponse, Http404, HttpResponseRedirect
from forms import *


''' vistas basdas en clases
from django.views.generic import TemplateView

class IndexView(TemplateView):
	template_name = 'home/index.html'
''' 

####Vistas basadas en funciones
def agregar_usuario(request):
	form=UserCreationEmailForm(request.POST or None)
	
	if request.method=="POST":
		if form.is_valid():
			form.save()
			return HttpResponseRedirect("/")

	return render(request, 'login.html',{'form':form})

def entrar(request):
	form=EmailAuthenticationForm(request.POST or None)
	if form.is_valid():
		login(request, form.get_user())
		return HttpResponseRedirect("listaPacientes")
	return render (request, 'usuario/Entrar.html',{'form':form})

Centro_Proyecto/templates/usuario/Entrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Centro de Dialisis Cornelio Samaniego</title>
    {%load static from staticfiles%}
    <link rel="icon" type="image/x-icon" href="{%static 'img/favicon.ico'%}" />
    <link rel="stylesheet" type="text/css" href="{%static 'css/normalize.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.css'%}" media="screen">    
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.css.map'%}" media="screen">    
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}" media="screen">    
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap-theme.css'%}" media="screen">  
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap-theme.min.css'%}" media="screen">  
    <link rel="stylesheet" type="text/css" href="{%static 'css/estilo1.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/estilo.css'%}">

    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.slides.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/interactividad.js'%}"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>      
</head>
<body>
    <!--ENCABEZADO CON HEADER-->
    <header>
               
        <!--IMAGEN DE LA IZQUIERDA--> 

        <div class="contenedor">
            <div class="imagenIzq">
                <figure>
                    <img src="{%static 'img/logo1.png' %}" alt="Centro de Dialisis">
                </figure>
            </div>
            
            <!---MENU-->
            <nav class="menu">
                <ul>
                    <li class="active">

                        <a href="{% url "home:home" %}">Regresar</a>
                    </li>
                    
                    <li> 
                        <a class="MainMenu-link" href="{# url "home:home" #}">Sistema de Centro de Dialisis</a>
                    </li>
                    
                </ul>
            </nav>
        </div>

    </header>
       <section id="Quienes Somos" class="Quienes Somos">

            <div class="u-containerDefault">
                <h2 class="Profile-title u-title">Login</h2>
                <p class="Profile-description">
                       <div class="login">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                        <input class= "sub btn btn-primary" type="submit" value="Ingresar al sistema">
                    </div>  
                        
            </div>
        </section>
    
<!--FOOTER-->

    <footer>
        <div id="titFooter">
            <h3>
                <strong>© 2015 Desarrollo Web</strong>
            </h3>
        </div>
        <div class="siguenos">
            <a href=""><img src="{%static 'img/facebook_logo.png' %}">Facebook</a>
            <a href=""><img src="{%static 'img/twitter_logo.png' %}">Twitter</a>
            <a href=""><img src="{%static 'img/instagram_logo.png' %}">Instagram</a>            
        </div>
    </footer>

</body>
</html>

Centro_Proyecto/templates/usuario/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial=1, maximum-scale=1">
    <title>Centro de Dialisis</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/style.css">
    

</head>
<body>
    <!--cabecera-->
    <header>
        <div class="logo">
                <img src="../static/img/medicina.jpg">
        </div>
        <div class="titulo">
            <h1 class="t">Centro de Dialisis "Cornelio Samaniego"</h1>
        
        </div>
        <!--
        <div class="menu1">
            <a class="home"href="#">Inicio</a>
            <a href="servicios" class="servicios">Servicios</a>
            -->
        <div class="bienvenido" >
            <h5 class"bienv">Bienvenido {{request.user}}</h5>   
        </div>
            
        </div>
        <div class="avatar">
            <figure class="av">
                <img src="../static/img/doctor.jpg" alt="doc">
            </figure>
        
        </div>
    </header>
    <!--navegación-->
    <nav class="nav2">
        <ul class="menu2 ">
            <li ><a href="{% url "index" %}">Inicio</a></li>
            <li><a class="primary" href="#">Servicios</a></li>
            <li ><a class="mary" href="#">Seguridad</a></li>
            
        </ul>
    </nav>
    <!--sección-->
    <section class="Pacientes">
    <div class="contorno">
    <nav>
        <ul class="menu nav nav-tabs">
            {%for seg in seguro%}
            <li><a class="button btn-primary" href="{%url "seguro" seg.pk%}">{{seg}}</a></li>
            {%endfor%}  
        </ul>
    </nav>
        
        <article class="pacien">
            <h3 class="title">Registrar Usuarios</h3>
             <div class="login">
                    <form action="/index/" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                    <input class= "sub" type="submit" value="Registrar">
                    </form>
                </div>.
        </article>
        
        </div>
        <aside class="ayuda">
            <h2>Panel de Control</h2>
            <div class="agregar">
                <a href="{% url "add" %}">Agregar Nuevo Paciente</a>
            </div>
            <div class="agregar">
                <p href="{% url "agregar_usuario" %}">Agregar Nuevo Usuario</p>
            </div>
            
            <div class="citas">
                contenido de citas
            </div>
        </aside>
    </section>
    <!--pIE DE pAGINA-->
    <footer class="final">
        <h3>
            <strong>Copyright -2015- </strong>
            <span class="copy">Loja-Ecuador</span>
        </h3>
    </footer>
    
</body>
</html>