Centro_Proyecto/Centro_Proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Centro_Proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('apps.home.urls', namespace="home")),
    url(r'', include ('apps.usuario.urls',namespace="usuario")),
    url(r'', include('apps.paciente.urls',namespace="paciente")),
    url(r'', include('apps.medicacion.urls',namespace="medicacion")),
    url(r'', include('apps.receta.urls',namespace="receta")),
    url(r'', include('apps.seguro.urls', namespace="seguro")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),### para servir imagenes
)
 

Centro_Proyecto/apps/medicacion/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	
	url(r'^receta/(\d+)$' , "apps.medicacion.views.MedicacionPacientes", name="medicacionPacientes"),
	url(r'^recetaPacientes/(\d+)$' , "apps.medicacion.views.recetaPacientes", name="recetaPacientes"),
	url(r'^agregarMedicamento/(\d+)$' , "apps.medicacion.views.agregarMedicamento", name="agregarMedicamento"),
	url(r'^eliminarMedicamento/(\d+)$' , "apps.medicacion.views.eliminarMedicamento", name="eliminarMedicamento"),
	url(r'^respuesta$' , "apps.medicacion.views.respuesta", name="respuesta"),
	url(r'^respuesta2$' , "apps.medicacion.views.respuesta", name="respuesta"),
	
)

Centro_Proyecto/apps/paciente/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^listaPacientes$' , "apps.paciente.views.listaPacientes", name='listaPacientes'),
	url(r'^eliminarPaciente/(\d+)$' , "apps.paciente.views.eliminarPaciente", name='eliminarPaciente'),
	url(r'^agregarPaciente$' , "apps.paciente.views.agregarPaciente", name="agregarPaciente"),
	url(r'^buscarPaciente$' , "apps.paciente.views.buscarPaciente", name="buscarPaciente"),
	url(r'^cerrar$' , "apps.paciente.views.cerrar", name="cerrar"),
	url(r'^historia/(\d+)$' , "apps.paciente.views.historia", name="historia"),


)

Centro_Proyecto/apps/paciente/models.py
from django.db import models
from apps.seguro.models import Seguro

class Paciente(models.Model):
	Numero_Historia=models.PositiveIntegerField(max_length=4, primary_key=True, unique=True, null=False)
	activo=models.BooleanField(default=True)
	Mujer="Mujer"
	Hombre="Hombre"
	cedula=models.IntegerField( unique=True)
	nombre=models.CharField(max_length=140)
	apellido=models.CharField(max_length=140)
	Sexos=((Mujer, "Mujer"), (Hombre, "Hombre"))
	sexo=models.CharField(max_length=20, choices=Sexos,default=Hombre)
	foto=models.ImageField(upload_to="fotos")
	ciudad=models.CharField(max_length=140)
	correo=models.EmailField()
	direccion=models.CharField( max_length=140)
	representanteLegal=models.CharField(max_length=140)
	fechaIngreso=models.DateField(auto_now=True)
	edad=models.PositiveIntegerField()
	Fecha_nacimiento=models.DateField()
	nacionalidad=models.CharField(max_length=140)
	grado_de_Instruccion=models.CharField(max_length=140)
	descripcion_clinica=models.TextField()
	seguro=models.ForeignKey(Seguro)
		
	def __unicode__(self):
		return "%s -%s"% (self.nombre, self.apellido)

Centro_Proyecto/apps/paciente/forms.py
from models import *
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.admin.widgets import AdminDateWidget 
from django.contrib.admin import widgets  


class PacienteForm(forms.ModelForm):
	class Meta:
		model=Paciente
	def __init__(self, *args, **kwargs):
		super(PacienteForm, self).__init__(*args, **kwargs)
		##self.fields['Fecha_nacimiento'].widget = forms.DateField(widget=widgets.AdminDateWidget)

		##self.fields['Fecha_nacimiento'] = forms.DateField(widget = widgets.AdminDateWidget())
		self.fields['cedula'].widget.attrs.update({'placeholder' : 'Ingrese el cedula','id':'cedula', 'title': "Se necesita una cedula", 'class':"form-control a", 'type':'text', 'required':'True','onkeydown':"return validarNumeros(event)"})	
		self.fields['nombre'].widget.attrs.update({'placeholder' : 'Ingrese el nombre','id':'pacienteF', 'title': "Se necesita un nombre(solo letras)", 'class':"form-control", 'type':'text', 'required':'True','onkeydown':"return validarLetras(event)"})	
		self.fields['Numero_Historia'].widget.attrs.update({'placeholder' : 'Ingrese el Numero_Historia','id':'pacienteF', 'title': "Se necesita un Numero_Historia(solo letras)", 'class':"form-control", 'type':'text', 'required':'True','onkeydown':"return validarNumeros(event)"})	
		self.fields['foto'].widget.attrs.update({'id':'pacienteF'})	
		self.fields['sexo'].widget.attrs.update({'id':'pacienteF'})	
		self.fields['apellido'].widget.attrs.update({'placeholder' : 'Ingrese el apellido','id':'pacienteF', 'title': "Se necesita un apellido", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarLetras(event)"})
		self.fields['correo'].widget.attrs.update({'placeholder' : 'Ingrese el correo','id':'pacienteF', 'title': "Se necesita un correo", 'class':"form-control", 'type':'text','required':'True'})
		self.fields['ciudad'].widget.attrs.update({'placeholder' : 'Ingrese el ciudad','id':'pacienteF', 'title': "Se necesita un ciudad", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarLetras(event)"})
		self.fields['direccion'].widget.attrs.update({'placeholder' : 'Ingrese el direccion','id':'pacienteF', 'title': "Se necesita un direccion", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarLetras(event)"})
		self.fields['Fecha_nacimiento'].widget.attrs.update({'placeholder' : 'DD/MM/AAAA','id':'pacienteF', 'title': "Se necesita un Fecha_nacimiento", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarNumeros(event)"})
		self.fields['representanteLegal'].widget.attrs.update({'placeholder' : 'Ingrese el representante Legal','id':'pacienteF', 'title': "Se necesita un representante Legal", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarLetras(event)"})
		self.fields['edad'].widget.attrs.update({'placeholder' : 'Ingrese el edad','id':'pacienteF', 'title': "Se necesita un edad", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarNumeros(event)"})
		self.fields['nacionalidad'].widget.attrs.update({'placeholder' : 'Ingrese el Nacionalidad','id':'pacienteF', 'title': "Se necesita un Nacionalidad", 'class':"form-control", 'type':'text','required':'True'})
		self.fields['grado_de_Instruccion'].widget.attrs.update({'placeholder' : 'Ingrese el Grado de Instruccion','id':'pacienteF', 'title': "Se necesita un Grado de Instruccion", 'class':"form-control", 'type':'text','required':'True','onkeydown':"return validarLetras(event)"})
		self.fields['descripcion_clinica'].widget.attrs.update({'placeholder' : 'Ingrese el Descripcion Clinica','id':'pacienteF', 'title': "Se necesita un Descripcion Clinica", 'class':"form-control", 'type':'text','required':'True'})
		self.fields['sexo'].widget.attrs.update({'class':'pacienteF'})


class BusquedaForm(forms.Form):
    buscar = forms.CharField(max_length=4,widget=forms.TextInput(attrs={'class':'buscar', 'onkeydown':'return validarNumeros(event)','placeholder' : 'Buscar','title':'Ingresar Historia Clinica','class':"form-control"}))

Centro_Proyecto/apps/paciente/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from apps.seguro.models import Seguro
from models import Paciente
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render_to_response
from forms import PacienteForm, BusquedaForm
from django.template.context import RequestContext

###listado de todos los pacientes###
@login_required
def listaPacientes(request):
	usuario=request.user
	seguro=Seguro.objects.all()
	paciente=Paciente.objects.order_by("-nombre").all()

	if request.method =='GET':
		form=BusquedaForm(request.GET)
		if form.is_valid():
			#Nombre=Receta(nombre=request.GET['su_nombre']) 
			#Nombre.save()
			Busqueda=request.GET['buscar']
			pacienteBus=Paciente.objects.filter(Numero_Historia=Busqueda)

			template="paciente/buscar.html"
			return render_to_response(template,context_instance=RequestContext(request,locals()))
			#return HttpResponseRedirect('/prueba')
	else:
		form=PruebaForm()
	
	template="paciente/paciente.html"
	return render_to_response(template,context_instance=RequestContext(request,locals()))


def eliminarPaciente(request, id_paciente):
	paciente=Paciente.objects.get(Numero_Historia=id_paciente)
	paciente.delete()
	return HttpResponseRedirect("/listaPacientes")



###Agregar Pacientes###
@login_required
def agregarPaciente(request):
	seguro=Seguro.objects.all()
	if request.POST:
		form=PacienteForm(request.POST, request.FILES)
		if form.is_valid():
			seguro=form.save(commit=False)
			seguro.usuario=request.user
			seguro.save()
			return HttpResponseRedirect("/listaPacientes")
	else:
		form=PacienteForm()
	
	template="paciente/pacientesForm.html"
	return render_to_response(template,context_instance=RequestContext(request,locals()))

@login_required
def historia(request, id_paciente):
	paciente=Paciente.objects.filter(cedula=id_paciente)
	template="paciente/historia.html"
	return render(request,template, locals())

##Buscar Por paciente##
@login_required
def buscarPaciente(request):
	if request.method =='GET':
		form=BusquedaForm(request.GET)
		if form.is_valid():
			#Nombre=Receta(nombre=request.GET['su_nombre']) 
			#Nombre.save()
			Busqueda=request.GET['buscar']
			paciente=Paciente.objects.filter(Numero_Historia=Busqueda)

			template="paciente/buscar.html"
			return render_to_response(template,context_instance=RequestContext(request,locals()))
			#return HttpResponseRedirect('/prueba')
	else:
		form=PruebaForm()
	
	template= 'base.html'
	return render_to_response(template,context_instance=RequestContext(request,locals()))
	





##Cerrar cesion##
@login_required
def cerrar(request):
    logout(request)
    return HttpResponseRedirect('/')

Centro_Proyecto/templates/paciente/buscar.html
{% extends "base.html" %}
{%block title%}busqueda{%endblock%}
	
{% block contenido %}
<div class="contenedor">
	<div id="contenidoB">
		<div class="page-header clearfix"> 
			
			<a id="registrar" href="{%url 'paciente:listaPacientes'%}"> <span class="glyphicon glyphicon-arrow-left"></span> Regresar </p>
		
		</div>
					<a id="registrar" href="{%url 'paciente:listaPacientes'%}"> Resultados de Busqueda</p>	
						<div id="animacion_pac">
						{% if pacienteBus %}
	    				
	    				<div class="datos">
						

						{%for pac in pacienteBus%}
						<div id="citas">

							<table class="table table-bordered">
								<tr>
									<td rowspan="7" width="4cm"> 
										<img id="img_paciente" src="{{pac.foto.url}}" alt="..." class="img-rounded"> <br>
										

									</td>
								</tr>


								<br >
								
								<tr> 
									<td width="20%"> Nombre: </td>
									<td width="50%"> {{pac.nombre}} </td>

									<td rowspan="2" width="20%"> 
										<span> <a  href="{%url "paciente:historia" pac.cedula%}">Ver Historia Clinica Completa</a></span>
									</td>

									
								</tr>

								<tr> 
									<td> Apellido: </td>
									<td> {{pac.apellido}} </td>

								</tr>
								<tr>
									<td> Direccion: </td>
									<td>{{pac.direccion}} </td>
									<td rowspan="2" width="20%"> 
										<span> <a  href="{%url "medicacion:medicacionPacientes" pac.pk%}">Medicamentos</a></span>
									</td>	
								</tr>

								<tr>
									<td> Estado: </td>
									{%if not pac.activo%}
										<td>Inactivo</td>
									{%else%}
										<td>Activo</td>			
									{%endif%}
										
								</tr>


								<tr>
								</tr>
							</div>

									{%endfor%}
								{% else %}
		    					NO HAY PACIENTES GUARDADOS
								{% endif %}

							</table>

						</div>


						</div>

					</div>
					</div>
{% endblock %}

Centro_Proyecto/templates/paciente/historia.html
{% extends "base.html" %}
{%block title%}HIstoria clinica{%endblock%}
	
{% block contenido %}
				{% for pac in paciente%}
				
				<div class="contenedor">
					<div id="contenidoH">
		
						<td width="10%"><div class="page-header"> 
						
								
							<h2 id="titulo5"> <img id="img_paciente" src="{{pac.foto.url}}" alt="..." class="img-rounded"></span> Paciente: <small> {{pac.nombre}}  </small> </h2>
						</div>
									<a  id="pac" class="btn btn-primary">{{pac.pk}}</a>
								<p class="text-info" id="numh">Numero Clinica del Paciente</p>
						<center>
							<table id="datos_personalesH" class="table table-hover table table-bordered">
								<tr> 
									<td width="30%"> Nombre: </td>
									<td> {{pac.nombre}} </td>
								</tr>
								<tr> 
									<td> Apellido: </td>
									<td> {{pac.apellido}} </td>
								</tr>
								<tr>
									<td> Direccion: </td>
									<td> {{pac.nombre}} </td>
								</tr>
								<tr> 
									<td> Cedula: </td>
									<td> {{pac.cedula}} </td>
								</tr>
								<tr> 
									<td> sexo </td>
									<td> {{pac.sexo}} </td>						
								</tr>
								<tr> 								
									<td> correo </td>
									<td> {{pac.correo}} </td>
								</tr>

								<tr> 								
									<td> Representante legal </td>
									<td> {{pac.representanteLegal}} </td>
								</tr>
								<tr> 								
									<td> FechaIngreso </td>
									<td> {{pac.fechaIngreso}} </td>
								</tr>
								<tr> 								
									<td> Edad </td>
									<td> {{pac.edad}} </td>
								</tr>
								<tr> 								
									<td> Fecha Nacimiento </td>
									<td> {{pac.Fecha_nacimiento}} </td>
								</tr>
								<tr> 								
									<td> Nacionalidad </td>
									<td> {{pac.nacionalidad}} </td>
								</tr>
								<tr> 								
									<td> Grado de Instruccion </td>
									<td> {{pac.grado_de_Instruccion}} </td>
								</tr>
								<tr> 								
									<td> Descripcion clinica </td>
									<td> {{pac.descripcion_clinica}} </td>
								</tr>
								<tr> 								
									<td> Seguro </td>
									<td> {{pac.seguro}} </td>
								</tr>
								
										<tr>
																
							</tr>
						

							</table>

						</center>
				


					
					</div>
					</div>
					{% endfor %}
{% endblock %}

Centro_Proyecto/templates/paciente/paciente.html
{% extends "base.html" %}
{%block title%}Listado de pacientes{%endblock%}
	
{% block contenido %}


<div class="contenedor">

	<div id="contenidoB">
		<div class="page-header clearfix"> 
		<p  id="registrar"> <span class="glyphicon glyphicon-book"></span> Listado de todos los Pacientes: </p>
		</div>

		<div id="tipo_institucion" class="pull-left">			
				<ul class="nav nav-pills " >
				  	{%for seg in seguro%}
						<li><button class="btn btn-primary seguroBtn" id="{{seg.pk}}" href="{#url "seguro" seg.pk#}">{{seg}}</a></li>
					 {%endfor%}					  
				</ul>
		</div>
		<div class="formulario">
		
		<form action="" method="GET" id="buscador-form">
				{% csrf_token %}
				{%for field in form%}
					<div id="buscador">{{field}}</div>
				<input type="submit" id="buscador-submit" value="" />
			  	{%endfor%}	  
			</form>

	</div>
						
						{% if paciente %}
	    				
	    				{%for pac in paciente%}
						<div id="citas">


							<table class="table table-bordered">
								<tr>
									<td rowspan="5" width="4cm"> 
										<img id="img_paciente" src="{{pac.foto.url}}" alt="..." class="img-rounded"> <br>
										

									</td>
								</tr>

								
								<tr> 
									<td width="20%"> Nombre: </td>
									<td width="50%"> {{pac.nombre}} </td>

									<td rowspan="2" width="20%"> 
										<span> <a  href="{%url "paciente:historia" pac.cedula%}">Ver Historia Clinica Completa</a></span>
									</td>
										<td rowspan="2" width="20%"> 
										<span> <a href="{%url "paciente:eliminarPaciente" pac.Numero_Historia %}">Eliminar Paciente</a></span>
									</td>

									
								</tr>

								<tr> 
									<td> Apellido: </td>
									<td> {{pac.apellido}} </td>

								</tr>
								<tr>
									<td> Historia Clinica: </td>
									<td>{{pac.Numero_Historia}} </td>
									<td rowspan="2" width="20%"> 
										<span> <a  href="{%url "medicacion:medicacionPacientes" pac.Numero_Historia%}">Medicamentos</a></span>
									</td>	
								</tr>

								<tr>
									<td> Estado: </td>
									{%if not pac.activo%}
										<td>Inactivo</td>
									{%else%}
										<td>Activo</td>			
									{%endif%}
										
								</tr>


								<tr>
								</tr>

									{%endfor%}
								{% else %}
		    					NO HAY PACIENTES GUARDADOS
								{% endif %}
							</table>
						</div>
	</div>
						

{% endblock %}

Centro_Proyecto/templates/paciente/pacientesForm.html
{% extends "base.html" %}
{% block contenido %}
	
	<div id="contenidoH">
		<div class="panel panel-default">
  			<div class="panel-heading">
				<p class="text-info" id="registrar">Registrar Nuevo Paciente</p>		
  			</div>
	
				<div class="formularioPac">
				
					<form method="post" enctype="multipart/form-data" class="form-group">
						<div action =" " id="form">
							{%csrf_token%}	
							
							{{form.as_p}}
							<center><input type="submit" class="btn btn-primary" value="Guardar Datos de paciente">		</center>
						</div>
					</form>
				</div>
		</div>
	</div>



{% endblock %}